import javax.swing.DefaultListModel;
import javax.swing.ListModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Test
 */
public class ROM extends javax.swing.JFrame {
    public ROM() {
        setVisible(rootPaneCheckingEnabled);
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setToolTipText("");

        jList1.setModel(new javax.swing.DefaultListModel<String>() {
            String[] strings = { "FC00    FF", "FC01    FF", "FC02    FF", "FC03    FF", "FC04    FF", "FC05    FF", "FC06    FF", "FC07    FF", "FC08    FF", "FC09    FF", "FC0A    FF", "FC0B    FF", "FC0C    FF", "FC0D    FF", "FC0E    FF", "FC0F    FF", "FC10    FF", "FC11    FF", "FC12    FF", "FC13    FF", "FC14    FF", "FC15    FF", "FC16    FF", "FC17    FF", "FC18    FF", "FC19    FF", "FC1A    FF", "FC1B    FF", "FC1C    FF", "FC1D    FF", "FC1E    FF", "FC1F    FF", "FC20    FF", "FC21    FF", "FC22    FF", "FC23    FF", "FC24    FF", "FC25    FF", "FC26    FF", "FC27    FF", "FC28    FF" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("ROM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        

        pack();
    }// </editor-fold>                        
    void storeAToMemory(String param, String A) {
        //DefaultListModel<String> model = (DefaultListModel<String>) jList1.getModel();
        if (!(jList1.getModel() instanceof DefaultListModel)) {
            jList1.setModel(new DefaultListModel<String>());
        }
        DefaultListModel<String> model = (DefaultListModel<String>) jList1.getModel();
        int index = -1; // Initialize index to -1
        for (int i = 0; i < model.getSize(); i++) {
            String element = model.getElementAt(i);
            String firstPart = element.split("\\s+")[0]; // Split the string by whitespace and get the first part
            if (firstPart.equals(param)) {
                index = i; // Set index to the current value of i
                // Exit the loop once a match is found
                break;
            }
        }
        // Use the value of index as needed
        if (index != -1) {
            // Match found, perform actions using index
            String element = model.getElementAt(index);
            String[] parts = element.split("\\s+");
            parts[1] = A; // Replace the value of the second column with A
            String updatedElement = String.join(" ", parts);
            model.setElementAt(updatedElement, index);
        } else {
            // No match found
        }
        //return false; // No match found
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ROM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ROM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ROM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ROM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ROM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
